name: SSH to VM and run commands

on:
  push:
    branches:
      - master  # Change this to your branch name

jobs:
  ssh_to_vm_and_run_commands:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH to VM and run commands
      env:
        VM_USERNAME: ${{ secrets.USER }}
        VM_PASSWORD: ${{ secrets.PASS }}
        VM_IP: ${{ secrets.VM_IP }}
      run: |
        sshpass -p $VM_PASSWORD ssh -o StrictHostKeyChecking=no $VM_USERNAME@$VM_IP << 'EOF'
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          sudo chmod 777 /etc/rancher/k3s/k3s.yaml
          cd tme6-7-8
          cd k8s
          kubectl apply -f redis.yaml
          kubectl apply -f redis-node.yml
          kubectl apply -f react.yml
          helm uninstall prometheus -n monitoring
          helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring
        
          
        EOF
