name: SSH to VM and run commands

on:
  push:
    branches:
      - master  # Change this to your branch name

jobs:
  ssh_to_vm_and_run_commands:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH to VM and run commands
      env:
        VM_USERNAME: ${{ secrets.USER }}
        VM_PASSWORD: ${{ secrets.PASS }}
        VM_IP: ${{ secrets.VM_IP }}
      run: |
        sshpass -p $VM_PASSWORD ssh -o StrictHostKeyChecking=no $VM_USERNAME@$VM_IP << 'EOF'
          ls
        EOF
